# Generated by Django 5.0.14 on 2026-01-24 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Identyfikator"
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[("DOG", "Pies"), ("CAT", "Kot"), ("OTHER", "Inny")],
                        max_length=10,
                        verbose_name="Gatunek",
                    ),
                ),
                (
                    "breed",
                    models.CharField(blank=True, max_length=100, verbose_name="Rasa"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Imię")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data urodzenia"
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("MALE", "Samiec"),
                            ("FEMALE", "Samica"),
                            ("UNKNOWN", "Nieznana"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                        verbose_name="Płeć",
                    ),
                ),
                (
                    "coat_color",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kolor sierści"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Waga (kg)",
                    ),
                ),
                (
                    "identifying_marks",
                    models.TextField(blank=True, verbose_name="Znaki szczególne"),
                ),
                (
                    "transponder_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Numer transpondera (chip)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW_INTAKE", "Nowo przyjęte"),
                            ("IN_SHELTER", "W schronisku"),
                            ("QUARANTINE", "Kwarantanna"),
                            ("MEDICAL_TREATMENT", "Leczenie"),
                            ("ADOPTED", "Adoptowane"),
                            ("DECEASED", "Zmarłe"),
                        ],
                        default="NEW_INTAKE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Uwagi")),
                (
                    "intake_date",
                    models.DateField(auto_now_add=True, verbose_name="Data przyjęcia"),
                ),
                (
                    "microchipping_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data chipowania"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Zwierzę",
                "verbose_name_plural": "Zwierzęta",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalProcedure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("procedure_date", models.DateField(verbose_name="Data zabiegu")),
                ("description", models.TextField(verbose_name="Opis zabiegu")),
                ("result", models.TextField(verbose_name="Wynik/Przebieg")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Koszt (PLN)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notatki dodatkowe"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures",
                        to="animals.animal",
                        verbose_name="Zwierzę",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_procedures",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Wykonał",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zabieg medyczny",
                "verbose_name_plural": "Zabiegi medyczne",
                "ordering": ["-procedure_date"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(max_length=200, verbose_name="Nazwa leku"),
                ),
                ("dosage", models.CharField(max_length=100, verbose_name="Dawkowanie")),
                (
                    "frequency",
                    models.CharField(
                        max_length=100, verbose_name="Częstotliwość podawania"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Data rozpoczęcia")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data zakończenia"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Powód przepisania")),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notatki dodatkowe"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="animals.animal",
                        verbose_name="Zwierzę",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescribed_medications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Przepisał",
                    ),
                ),
            ],
            options={
                "verbose_name": "Przepisany lek",
                "verbose_name_plural": "Przepisane leki",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vaccine_name",
                    models.CharField(max_length=200, verbose_name="Nazwa szczepionki"),
                ),
                (
                    "vaccine_for",
                    models.CharField(
                        max_length=200, verbose_name="Przeciwko (chorobie)"
                    ),
                ),
                (
                    "vaccine_batch_number",
                    models.CharField(max_length=100, verbose_name="Numer partii"),
                ),
                ("vaccination_date", models.DateField(verbose_name="Data szczepienia")),
                ("expiration_date", models.DateField(verbose_name="Data wygaśnięcia")),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data następnego szczepienia",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="animals.animal",
                        verbose_name="Zwierzę",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administered_vaccinations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Wykonał",
                    ),
                ),
            ],
            options={
                "verbose_name": "Szczepienie",
                "verbose_name_plural": "Szczepienia",
                "ordering": ["-vaccination_date"],
            },
        ),
    ]
