# Generated by Django 5.0.14 on 2026-01-30 01:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehavioralTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "behavioral_tag_name",
                    models.CharField(
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Behavioral Tag Name",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Behavioral Tag",
                "verbose_name_plural": "Behavioral Tags",
                "ordering": ["-behavioral_tag_name"],
            },
        ),
        migrations.CreateModel(
            name="Intake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intake_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Intake Identifier",
                    ),
                ),
                ("intake_date", models.DateField(verbose_name="Intake Date")),
                (
                    "animal_condition",
                    models.CharField(max_length=255, verbose_name="Animal Condition"),
                ),
                ("location", models.CharField(max_length=255, verbose_name="Location")),
                ("notes", models.CharField(max_length=255, verbose_name="Notes")),
                (
                    "intake_type",
                    models.CharField(
                        choices=[
                            ("STRAY", "Stray"),
                            ("SURRENDER", "Surrender"),
                            ("CONFISCATION", "Confiscation"),
                            ("TRANSFER", "Transfer"),
                            ("BORN_IN_SHELTER", "Born in Shelter"),
                        ],
                        max_length=20,
                        verbose_name="Intake Type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intakes",
                        to="animals.animal",
                        verbose_name="Animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intake",
                "verbose_name_plural": "Intakes",
                "ordering": ["-intake_date", "-intake_type"],
            },
        ),
    ]
