# Generated by Django 5.0.14 on 2026-02-02 08:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0002_behavioraltag_intake"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Photo Identifier",
                    ),
                ),
                ("url", models.CharField(max_length=255, verbose_name="URL")),
                ("filename", models.CharField(max_length=100, verbose_name="Filename")),
                (
                    "upload_date",
                    models.DateField(auto_now_add=True, verbose_name="Upload Date"),
                ),
                (
                    "is_identification_photo",
                    models.BooleanField(
                        default=True, verbose_name="Is Identification Photo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
                "ordering": ["-created_at"],
            },
        ),
    ]
