# Generated by Django 5.0.14 on 2026-02-02 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0003_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="behavioral_tags",
            field=models.ManyToManyField(
                blank=True, related_name="animals", to="animals.behavioraltag"
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="last_measured",
            field=models.DateField(
                blank=True, null=True, verbose_name="Lasr measured date"
            ),
        ),
        migrations.AddField(
            model_name="intake",
            name="source_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="Source Identifier"
            ),
        ),
        migrations.AddField(
            model_name="intake",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[("person", "person"), ("institution", "institution")],
                max_length=20,
                null=True,
                verbose_name="Source Type",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="animal_id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=50,
                unique=True,
                verbose_name="Identyfikator",
            ),
        ),
    ]
