# Generated by Django 5.0.14 on 2026-02-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0004_animal_behavioral_tags_animal_last_measured_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="parents",
            field=models.ManyToManyField(
                blank=True, related_name="offspring", to="animals.animal"
            ),
        ),
    ]
