# Generated by Django 5.0.14 on 2026-02-02 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0005_animal_parents"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="animal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="animals.animal",
                verbose_name="Animal",
            ),
            preserve_default=False,
        ),
    ]
