# Generated by Django 5.0.14 on 2026-02-02 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0006_photo_animal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intake",
            name="intake_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Intake Date"
            ),
        ),
    ]
