# Generated by Django 5.0.14 on 2026-02-02 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0007_alter_intake_intake_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicalprocedure",
            options={
                "ordering": ["-procedure_date"],
                "verbose_name": "Medical Procedure",
                "verbose_name_plural": "Medical Procedures",
            },
        ),
        migrations.AlterModelOptions(
            name="medication",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Prescribed Medication",
                "verbose_name_plural": "Prescribed Medications",
            },
        ),
        migrations.AlterModelOptions(
            name="vaccination",
            options={
                "ordering": ["-vaccination_date"],
                "verbose_name": "Vaccination",
                "verbose_name_plural": "Vaccinations",
            },
        ),
        migrations.AlterField(
            model_name="animal",
            name="animal_id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=50,
                unique=True,
                verbose_name="Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="breed",
            field=models.CharField(blank=True, max_length=100, verbose_name="Breed"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="coat_color",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Coat Color"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="identifying_marks",
            field=models.TextField(blank=True, verbose_name="Identifying Marks"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="intake_date",
            field=models.DateField(auto_now_add=True, verbose_name="Intake Date"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="last_measured",
            field=models.DateField(
                blank=True, null=True, verbose_name="Last measured date"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="microchipping_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Microchipping Date"
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="sex",
            field=models.CharField(
                choices=[
                    ("MALE", "Male"),
                    ("FEMALE", "Female"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                max_length=10,
                verbose_name="Sex",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="species",
            field=models.CharField(
                choices=[("DOG", "Dog"), ("CAT", "Cat"), ("OTHER", "Other")],
                max_length=10,
                verbose_name="Species",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW_INTAKE", "Newly Intake"),
                    ("IN_SHELTER", "In Shelter"),
                    ("QUARANTINE", "Quarantine"),
                    ("MEDICAL_TREATMENT", "Medical Treatment"),
                    ("ADOPTED", "Adopted"),
                    ("DECEASED", "Deceased"),
                ],
                default="NEW_INTAKE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="transponder_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Transponder Number(microchip)",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Weight (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="medicalprocedure",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procedures",
                to="animals.animal",
                verbose_name="Animal",
            ),
        ),
        migrations.AlterField(
            model_name="medicalprocedure",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Cost"
            ),
        ),
        migrations.AlterField(
            model_name="medicalprocedure",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="medicalprocedure",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="medicalprocedure",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_procedures",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Performed by",
            ),
        ),
        migrations.AlterField(
            model_name="medicalprocedure",
            name="procedure_date",
            field=models.DateField(verbose_name="Procedure Date"),
        ),
        migrations.AlterField(
            model_name="medicalprocedure",
            name="result",
            field=models.TextField(verbose_name="Result/Progress"),
        ),
        migrations.AlterField(
            model_name="medication",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medications",
                to="animals.animal",
                verbose_name="Animal",
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="dosage",
            field=models.CharField(max_length=100, verbose_name="Dosage"),
        ),
        migrations.AlterField(
            model_name="medication",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="medication",
            name="frequency",
            field=models.CharField(
                max_length=100, verbose_name="Frequency of administration"
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="medication_name",
            field=models.CharField(max_length=200, verbose_name="Medication Name"),
        ),
        migrations.AlterField(
            model_name="medication",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="medication",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prescribed_medications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Prescribed by",
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="reason",
            field=models.TextField(verbose_name="Reason for prescription"),
        ),
        migrations.AlterField(
            model_name="medication",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vaccinations",
                to="animals.animal",
                verbose_name="Animal",
            ),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="expiration_date",
            field=models.DateField(verbose_name="Expiration Date"),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="next_due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Next Due Date"),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administered_vaccinations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Performed by",
            ),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="vaccination_date",
            field=models.DateField(verbose_name="Vaccination Date"),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="vaccine_batch_number",
            field=models.CharField(max_length=100, verbose_name="Batch Number"),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="vaccine_for",
            field=models.CharField(max_length=200, verbose_name="Vaccine For"),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="vaccine_name",
            field=models.CharField(max_length=200, verbose_name="Vaccine Name"),
        ),
    ]
