# Generated by Django 5.0.14 on 2026-02-09 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("animals", "0008_alter_medicalprocedure_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Animal",
                "verbose_name_plural": "Animals",
            },
        ),
    ]
