# Generated by Django 5.0.14 on 2026-01-24 22:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Aktualna ilość",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data ważności"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stan magazynowy",
                "verbose_name_plural": "Stany magazynowe",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nazwa dostawcy"),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
            ],
            options={
                "verbose_name": "Dostawca",
                "verbose_name_plural": "Dostawcy",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nazwa kategorii"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoria zaopatrzenia",
                "verbose_name_plural": "Kategorie zaopatrzenia",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nazwa jednostki"),
                ),
                ("abbreviation", models.CharField(max_length=10, verbose_name="Skrót")),
            ],
            options={
                "verbose_name": "Jednostka miary",
                "verbose_name_plural": "Jednostki miary",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InventoryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("IN", "Przyjęcie"), ("OUT", "Wydanie")],
                        max_length=3,
                        verbose_name="Typ operacji",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ilość"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Komentarz/Powód"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data i godzina"
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="supplies.inventory",
                        verbose_name="Stan magazynowy",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Wykonał",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operacja magazynowa",
                "verbose_name_plural": "Operacje magazynowe",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SupplyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nazwa zasobu"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "min_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Minimalny stan",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="supplies.supplycategory",
                        verbose_name="Kategoria",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="supplies.unitofmeasure",
                        verbose_name="Jednostka miary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zasób magazynowy",
                "verbose_name_plural": "Zasoby magazynowe",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="inventory",
            name="supply_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="supplies.supplyitem",
                verbose_name="Zasób",
            ),
        ),
        migrations.CreateModel(
            name="SupplyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data złożenia"
                    ),
                ),
                (
                    "expected_delivery_date",
                    models.DateField(verbose_name="Oczekiwana data dostawy"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "W realizacji"),
                            ("COMPLETED", "Zrealizowane"),
                            ("CANCELLED", "Anulowane"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Uwagi")),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="supplies.supplier",
                        verbose_name="Dostawca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zamówienie zaopatrzenia",
                "verbose_name_plural": "Zamówienia zaopatrzenia",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplyOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ilość"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="supplies.supplyorder",
                        verbose_name="Zamówienie",
                    ),
                ),
                (
                    "supply_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_lines",
                        to="supplies.supplyitem",
                        verbose_name="Zasób",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pozycja zamówienia",
                "verbose_name_plural": "Pozycje zamówienia",
            },
        ),
    ]
