# Generated by Django 5.0.14 on 2026-01-29 19:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Address Identifier"
                    ),
                ),
                ("city", models.CharField(max_length=50, verbose_name="City")),
                (
                    "postal_code",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Postal code must be in format: XX-XXX",
                                regex="^\\d{2}-\\d{3}$",
                            )
                        ],
                        verbose_name="Postal Code",
                    ),
                ),
                ("street", models.CharField(max_length=50, verbose_name="Street")),
                (
                    "building_number",
                    models.CharField(max_length=5, verbose_name="Building Number"),
                ),
                (
                    "apartment_number",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Apartment Number"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "ordering": ["-city", "-street", "-building_number"],
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution_id",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Institution Identifier",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Phone Number"),
                ),
                (
                    "email_address",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Email Address"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="institutions",
                        to="parties.address",
                        verbose_name="Address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution",
                "verbose_name_plural": "Institutions",
                "ordering": ["-name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Person Identifier"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Phone Number"),
                ),
                (
                    "email_address",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Email Address"
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "lastname",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persons",
                        to="parties.address",
                        verbose_name="Address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
                "ordering": ["-firstname", "-lastname"],
            },
        ),
    ]
