# Generated by Django 5.0.14 on 2026-01-30 01:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=50,
                unique=True,
                verbose_name="Address Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="institution_id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=50,
                unique=True,
                verbose_name="Institution Identifier",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="person_id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=50,
                unique=True,
                verbose_name="Person Identifier",
            ),
        ),
    ]
