# Generated by Django 5.0.14 on 2026-02-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0002_alter_address_address_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="email_address",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email_address",
            field=models.CharField(
                blank=True, max_length=50, unique=True, verbose_name="Email Address"
            ),
        ),
    ]
