# Generated by Django 5.0.14 on 2026-02-09 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Address Identifier",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Schedule Name")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Schedule",
                "verbose_name_plural": "Schedules",
                "ordering": ["-start_date", "-end_date"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=50,
                        unique=True,
                        verbose_name="Task Identifier",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Task Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Task Description"
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="Task Date and Time")),
                (
                    "duration_in_minutes",
                    models.PositiveIntegerField(
                        verbose_name="Task Duration in Minutes"
                    ),
                ),
                (
                    "maxVolunteers",
                    models.PositiveIntegerField(verbose_name="Maximum Volunteers"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="volunteers.schedule",
                        verbose_name="Schedule",
                    ),
                ),
                (
                    "volunteers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tasks_signed_up",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Volunteers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["-datetime"],
            },
        ),
    ]
