# Generated by Django 5.0.14 on 2026-02-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("volunteers", "0002_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Available"),
                    ("PERSON_LIMIT_REACHED", "Person Limit Reached"),
                    ("COMPLETED", "Completed"),
                    ("UNCOMPLETED", "Uncompleted"),
                ],
                max_length=20,
                verbose_name="Task Status",
            ),
        ),
    ]
